### PR TITLE
Fix loading nullable fields

### LINKED ISSUE #312: Nullable fields
When loading field we need to ensure that for the case of nullable fields, instead of GetColumn we use GetColumnNullable

### PR DESCRIPTION
**Pull request by christianparpart**
Closes #312

### CODE REVIEW

File: src/Lightweight/DataMapper/DataMapper.hpp [hunk 1]
```diff
@@ -161,11 +161,14 @@ void GetAllColumns(SqlResultCursor& reader, Record& record)
...
-                field.MutableValue() = reader->GetColumn<typename Field::ValueType>(indexFromQuery);
+                if constexpr (Field::IsOptional)
+                    field.MutableValue() = reader->GetNullableColumn<typename Field::ValueType::value_type>(indexFromQuery);
+                else
+                    field.MutableValue() = reader->GetColumn<typename Field::ValueType>(indexFromQuery);
             }
             else if constexpr (SqlGetColumnNativeType<Field>)
             {
-                if constexpr (IsOptionalBelongsTo<Field>)
+                if constexpr (Field::IsOptional)
```
Comment (Yaraslaut) [inline src/Lightweight/DataMapper/DataMapper.hpp:171]: We need to ensure that we use only belongs to fields here, so this change is not needed

**Review by Yaraslaut — CHANGES_REQUESTED** [review]
Comment and I would like to have tests for it

**Review by Yaraslaut — APPROVED** [review]
thanks :)
